eCommerce.Web/Controllers/AuthController.cs
using System;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using eCommerce.Domain.DTO;
using eCommerce.Domain.IService;
using eCommerce.Ultility.PasswordHandler;
using eCommerce.Ultility.Type;
using eCommerce.Web.Models;
using Microsoft.AspNet.Identity;
using System.Collections.Generic;
using System.Linq;
using PagedList;

namespace eCommerce.Web.Controllers
{
    public class AuthController : BaseController
    {
        private readonly IUserService _userService;
        private readonly IRoleService _roleService;
        private readonly IOrderService _orderService;

        public AuthController(IUserService userService, IRoleService roleService, IOrderService orderService)
        {
            _userService = userService;
            _roleService = roleService;
            _orderService = orderService;
        }

        public AuthController()
        {            
        }

        // GET: Auth/Register
        [AllowAnonymous]
        public ActionResult Register()
        {            
            return View("Register");
        }

        // POST: Auth/Register
        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register([Bind(Include = "UserName,Email,Password,RetypePassword,Address,PhoneNumber")] RegisterModel model)
        {
            if (!ModelState.IsValid) return View("Register", model);

            model.UserName = model.UserName.Replace(" ", "");
            if (_userService.CheckRegisterUsernameEmail(model.UserName, model.Email) != null)
            {
                ModelState.AddModelError("available", "Username/Email is already taken");
                return View("Register", model);
            }

            model.Id = Guid.NewGuid();
            model.Password = Encryption.Encrypt(model.Password);            
            model.RoleId = _roleService.GetRoleByName(RoleType.User.ToString()).Id;

            var userDto = Mapper.Map<RegisterModel, UserDTO>(model);            
            _userService.AddNewUser(userDto);
            LoginAccount(model.Id, model.UserName, RoleType.User.ToString());

            return RedirectToAction("Index", "Home");
        }

        // GET: Auth/Login        
        [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        // POST: Auth/Login
        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginModel model, string returnUrl)
        {
            if (!ModelState.IsValid) return View("Login", model);

            var user = _userService.CheckLoginUsernamEmail(model.UsernameEmail);
            if (user != null)
            {
                var decryptedPassword = Decryption.Decrypt(user.Password);
                if (model.Password == decryptedPassword && !user.IsDeleted)
                {                    
                    LoginAccount(user.Id, user.UserName, user.Role.Name);
                    return RedirectToLocal(returnUrl);
                }
            }

            ModelState.AddModelError("userpass", "Username/password is incorrect.");
            return View(model);
        }

        // GET: Auth/Manage
        [Authorize]
        public ActionResult Manage(string username,int page=1)
        {
            if (username == null) return Redirect("~/ErrorPages/404.html");

            if (User.Identity.Name != username) return RedirectToAction("Index", "Home");            
            var user = _userService.FindUserByName(username);            

            var ordersDto = _orderService.GetOrderByUserId(user.Id).Take(10);            
            var order = Mapper.Map<List<OrderDTO>, List<OrderManageViewModel>>(ordersDto.ToList());
            var data = new ManageUserAndOrder { RegisterModel = Mapper.Map<UserDTO, RegisterModel>(user), OrderManageViewModel = order };

            return View("Manage", data);
        }

        // POST: Auth/Manage
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Manage(ManageUserAndOrder model, string name, string email)
        {
            FillRecentOrders(model, name);
            if (!ModelState.IsValid) return View("Manage", model);


            if (_userService.CheckRegisterUsernameEmail(model.RegisterModel.UserName, model.RegisterModel.Email) != null &&
                model.RegisterModel.UserName != name && model.RegisterModel.Email != email)
            {
                ModelState.AddModelError("available", "Username/Email is already taken");
                return View("Manage", model);
            }

            model.RegisterModel.UserName = model.RegisterModel.UserName.Replace(" ", "");
            model.RegisterModel.Password = Encryption.Encrypt(model.RegisterModel.Password);
            var user = Mapper.Map<RegisterModel, UserDTO>(model.RegisterModel);
            _userService.UpdateUser(user);

            var role = _roleService.GetRoleById(model.RegisterModel.RoleId);
            LoginAccount(model.RegisterModel.Id, model.RegisterModel.UserName, role.Name);
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Logout()
        {
            var ctx = Request.GetOwinContext();
            var authManager = ctx.Authentication;

            authManager.SignOut(DefaultAuthenticationTypes.ApplicationCookie);
            Session.Clear();

            return RedirectToAction("Index","Home");
        }        

        #region AuthUtilities        
        private void LoginAccount(Guid id, string name, string role)
        {
            var identity = new ClaimsIdentity(new[]
            {
                new Claim(ClaimTypes.Name, name),
                new Claim(ClaimTypes.Role, role),
                new Claim(ClaimTypes.NameIdentifier, id.ToString())
            }, DefaultAuthenticationTypes.ApplicationCookie);

            var authManager = Request.GetOwinContext().Authentication;
            authManager.SignIn(identity);
        }

        private ActionResult RedirectToLocal(string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            return RedirectToAction("Index", "Home");
        }

        public ManageUserAndOrder FillRecentOrders(ManageUserAndOrder data, string username)
        {
            var user = _userService.FindUserByName(username);
            var ordersDto = _orderService.GetOrderByUserId(user.Id).Take(10);            
            var order = Mapper.Map<List<OrderDTO>, List<OrderManageViewModel>>(ordersDto.ToList());
            data.OrderManageViewModel = order;
            return data;
        }
        #endregion
    }
}

eCommerce.Web/Controllers/OrderController.cs
using AutoMapper;
using eCommerce.Domain.DTO;
using eCommerce.Domain.IService;
using eCommerce.Ultility;
using eCommerce.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;
using eCommerce.Ultility.EmailHandler;
using Microsoft.AspNet.Identity;

namespace eCommerce.Web.Controllers
{
    public class OrderController : BaseController
    {
        private readonly IProductService _productService;
        private readonly IOrderService _orderService;
        private readonly IUserService _userService;

        public OrderController(IProductService productService, IOrderService orderService, IUserService userService)
        {
            _productService = productService;
            _orderService = orderService;
            _userService = userService;
        }

        public ActionResult Index()
        {
            var ordersDto = _orderService.GetOrderByUserId(_userService.FindUserByName(User.Identity.Name).Id);
            var ordersVm = Mapper.Map<List<OrderDTO>, List<OrderManageViewModel>>(ordersDto.ToList());

            return View(ordersVm);
        }

        public ActionResult OrderDetail(Guid orderId)
        {
            var orderDetailsDto = _orderService.GetOrderDetail(orderId);
            var orderDetailsVm = Mapper.Map<List<OrderDetailDTO>, List<OrderDetailViewModel>>(orderDetailsDto.ToList());

            return View(orderDetailsVm);
        }

        public ActionResult AddToCart(Guid productId, string name, decimal price, string slug, string RepresentImg, int Stock)
        {
            UpdateCart(productId, null, name, price, slug, RepresentImg, Stock);
            var cart = (List<CartItem>)Session["Cart"];
            var data = cart.FirstOrDefault(x => x.ItemId == productId);
            return PartialView("_AddedToCart", data);
        }        

        public ActionResult CartPage()
        {
            ViewBag.IsCheckout = false;
            ValidateCart();
            return View(Session["Cart"]);
        }

        [Authorize]
        public ActionResult CheckoutPage()
        {
            ViewBag.IsCheckout = true;
            var userDto = _userService.FindUserByName(User.Identity.Name);
            var user = Mapper.Map<UserDTO, UserCheckoutModel>(userDto);

            ValidateCart();

            return View("Checkout", user);
        }

        public async Task<ActionResult> ProceedOrder()
        {
            var cart = (List<CartItem>)Session["Cart"];
            var cartForEmail = new List<string>();

            if (cart == null || cart.Count == 0)
            {
                TempData["Message"] = Constant.MESSAGE_ORDER_EMPTY;
                return RedirectToAction("Index", "Home");
            }
            var orderDetails = new List<OrderDetailDTO>();
            foreach (var x in cart)
            {
                orderDetails.Add(new OrderDetailDTO { Quantity = x.Quantity, ProductId = x.ItemId });
                AddItemToCartForEmail(cartForEmail, x);
            }

            var user = _userService.FindUserByName(User.Identity.Name);
            var orderId = _orderService.Create(user.Id, (int)Session["CartTotal"], orderDetails);

            cartForEmail.Add("Total Price: " + cart.Sum(c => c.Price * c.Quantity));
            cartForEmail.Add("ORDER ID: " + orderId);            

            //Clear session
            cart.Clear();
            Session["CartTotal"] = 0;

            // Send email to user.
            await CheckOutConfirmation.Send(user.Email, cartForEmail);
            return RedirectToAction("Confirmation");

        }        

        [HttpPost]
        public ActionResult AddToCartInDetailPage(Guid productId, int quantity)
        {
            var product = _productService.GetById(productId);
            UpdateCart(productId, quantity, product.Name, product.Price, product.UrlSlug, product.RepresentImg, product.Quantity);
            TempData["Message"] = quantity + " " + product.Name + " have been added to cart.";
            return RedirectToAction("Detail", "Product", new { slug = product.UrlSlug });
        }

        public ActionResult Confirmation()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult BillingInfo(string address, string phoneNumber)
        {
            var user = _userService.FindUserById(Guid.Parse(User.Identity.GetUserId()));
            user.Address = address;
            user.PhoneNumber = phoneNumber;
            _userService.UpdateUser(user);

            return RedirectToAction("CheckoutPage");
        }

        #region OrderFunctions
        private void UpdateCart(Guid id, int? quantity, string name, decimal price, string slug, string representImg, int Stock)
        {
            if (quantity == null)
                quantity = 1;
            List<CartItem> cart;
            if (Session["Cart"] == null)
            {
                cart = new List<CartItem>();
                cart.Add(new CartItem { ItemId = id, Quantity = (int)quantity, Name = name, Price = price, Slug = slug, RepresentImg = representImg });
                Session["Cart"] = cart;
                Session["CartTotal"] = quantity;
            }
            else
            {
                var itemExisted = false;
                cart = (List<CartItem>)Session["Cart"];
                foreach (var item in cart)
                {
                    if (item.ItemId == id)
                    {
                        itemExisted = true;
                        item.Quantity += (int)quantity;
      
                        break;
                    }
                }

                if (!itemExisted)
                {
                    cart.Add(new CartItem { ItemId = id, Quantity = (int)quantity, Price = price, Name = name, Slug = slug, RepresentImg = representImg });
                }

                Session["Cart"] = cart;
                Session["CartTotal"] = cart.Sum(x => x.Quantity);

            }

        }

        public void UpdateCartItem(string ItemId, string actionName)
        {
            var cart = (List<CartItem>)Session["Cart"];
            var item = cart.FirstOrDefault(x => x.ItemId == new Guid(ItemId));
            switch (actionName)
            {
                case "increase":
                    item.Quantity++;
                    break;
                case "decrease":
                    if (item.Quantity > 1)
                        item.Quantity--;
                    break;
                case "delete":
                    cart.Remove(item);
                    break;
            }

            Session["CartTotal"] = cart.Sum(x => x.Quantity);
        }                

        public void ValidateCart()
        {
            var exceedStock = false;
            var sb = new StringBuilder();
            sb.Append("The following item(s) have exceeded our stock. Their quantity has been adjusted: <br/>");

            // Validate products in cart actually exist in database and quantity does not exceed stock.
            var cart = (List<CartItem>)Session["Cart"];
            if (cart == null)
                return;
            for (int x = 0; x < cart.Count; x++)
            {
                var y = _productService.GetById(cart[x].ItemId);
                if (y == null)
                {
                    cart.RemoveAt(x);
                }
                if (y.Quantity < cart[x].Quantity)
                {
                    exceedStock = true;
                    sb.Append("<li>" + cart[x].Name + " (Original: " + cart[x].Quantity + ", Adjusted: " + y.Quantity + ")</li>");
                    Session["CartTotal"] = (int)Session["CartTotal"] + y.Quantity - cart[x].Quantity;
                    cart[x].Quantity = y.Quantity;
                    
                }
                if (exceedStock)
                {
                    TempData["Message"] = sb.ToString();
                }
            }
        }

        public void CancelOrder(Guid orderId)
        {
            _orderService.CancelOrder(orderId);
        }

        public void AddItemToCartForEmail(List<string> cartString, CartItem item)
        {
            var builder = new StringBuilder();
            builder.Append("Name: ");
            builder.Append(item.Name);
            builder.Append(" _ ");

            builder.Append("Price: ");
            builder.Append(item.Price);
            builder.Append(" _ ");

            builder.Append("Quantity: ");
            builder.Append(item.Quantity);
            builder.Append(" _ ");

            builder.Append("Total: ");
            builder.Append(item.Price * item.Quantity);            

            cartString.Add(builder.ToString());            
        }
        #endregion
    }
}

eCommerce.Web/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Gift4Charity</title>    
    @Styles.Render("~/Content/AdminStyle")        
</head>
<body>

    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>                
                <a class="navbar-brand" href="@Url.Action("Index", "Home")">Admin Page</a>                
            </div>
            <div id="navbar" class="navbar-collapse collapse">                
                <ul class="nav navbar-nav navbar-right">
                    @if (@User.Identity.IsAuthenticated)
                    {
                        <li>
                            <a href="@Url.Action("Manage", "Auth", new {username = User.Identity.Name, Area = ""})">
                                <i class="glyphicon glyphicon-user"></i> Welcome, @User.Identity.Name
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "Home", new {Area = ""})">
                                <i class="glyphicon glyphicon-home"></i> Homepage
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Logout", "Auth", new {Area = ""})">
                                <i class="glyphicon glyphicon-log-out"></i> Sign out
                            </a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2">
                <div class="sidebar content-box" style="display: block;">
                    <ul class="nav">
                        <!-- Main menu -->
                        <li>
                            <a href="@Url.Action("Index", "User")">
                                <i class="glyphicon glyphicon-user"></i>
                                Members
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "Category")">
                                <i class="glyphicon glyphicon-folder-open"></i>
                                Categories / Subcategories
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "Order")">
                                <i class="glyphicon glyphicon-shopping-cart"></i>
                                Orders
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "Product")">
                                <i class="glyphicon glyphicon-list"></i>
                                Products
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-10">
                <div class="sidebar content-box" style="display: block;">
                    @RenderBody()
                </div>                    
            </div>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/AdminScript")
    @RenderSection("scripts", required: false)
</body>
</html>